import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { PlayerContextProvider } from '@/context/players'
import { GameStateContextProvider } from '@/context/gameState'
import { RoomsContextProvider } from '@/context/rooms'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PlayerContextProvider>
          <GameStateContextProvider>
            <RoomsContextProvider>
              {children}
            </RoomsContextProvider>
          </GameStateContextProvider>
        </PlayerContextProvider>
      </body>
    </html>
  )
}
